version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: verv-user
      POSTGRES_PASSWORD: vervsuperpassword1
      POSTGRES_DB: voting_db
    volumes:
      - voter-vol:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - verv-vote-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: voting_db
      DB_USER: verv-user
      DB_PASSWORD: vervsuperpassword1
    depends_on:
      - db
    networks:
      - verv-vote-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - verv-vote-network

networks:
  verv-vote-network:
    driver: bridge

volumes:
  voter-vol: